"""empty message

Revision ID: 7bc30f3ebcdc
Revises: 
Create Date: 2019-08-04 12:53:40.573023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc30f3ebcdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_url',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('count', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('short_url')
    # ### end Alembic commands ###
