"""empty message

Revision ID: 95f2d158329c
Revises: 7bc30f3ebcdc
Create Date: 2019-08-04 12:58:40.416460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95f2d158329c'
down_revision = '7bc30f3ebcdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('short_url', 'url',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('short_url', 'url',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
